MvcApplication13/Controllers/FileUploadController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication13.Controllers
{
    public class FileUploadController : Controller
    {
        //
        // GET: /FileUpload/

        UploadEntities1 db = new UploadEntities1();

        //
        // GET: /FileUpload/

        public ActionResult List()
        {
            return View(db.Tables.ToList());
        }
        public ActionResult submit()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult submit(Table t, HttpPostedFileBase file)
        {

            if (file != null)
            {
                int MaxContentLength = 1024 * 1024 * 30; //30 MB
                string[] AllowedFileExtensions = new string[] { ".jpg", ".gif", ".png", ".pdf", ".html", ".htm", ".wmv", ".mp4", ".mp3", ".wav" };

                if (!AllowedFileExtensions.Contains(file.FileName.Substring(file.FileName.LastIndexOf('.'))))
                {
                    // ModelState.AddModelError("File", "Please file of type: " + string.Join(", ", AllowedFileExtensions));
                    ViewBag.Message = "Please file of type: " + string.Join(", ", AllowedFileExtensions);
                }

                else if (file.ContentLength > MaxContentLength)
                {
                    return Content("Your file is too large, maximum allowed size is: " + MaxContentLength + " MB");
                }
                else
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Upload"), fileName);


                    file.SaveAs(path);
                    ModelState.Clear();
                    ViewBag.Message = "File uploaded successfully";
                    string ds = file.FileName.Substring(file.FileName.Length - 3);
                    string p = string.Empty;
                    p = Server.MapPath("~/Content/Upload/");
                    file.SaveAs(p + file.FileName);

                    using(db)
                    {
                        t.file = file.FileName;
                        db.Tables.Add(t);
                        db.SaveChanges();
                    }
                }

            }
            else
            {
                return Content("Please Upload Your file");
            }
            return RedirectToAction("List");
        }

        public ActionResult Details(int id)
        {
            return View(db.Tables.Find(id));
        }

        public ActionResult Edit(int id)
        {
            return View(db.Tables.Find(id));
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(Table t, HttpPostedFileBase file)
        {
            if (file != null)
            {
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/Upload"), fileName);


                file.SaveAs(path);
                ModelState.Clear();
                ViewBag.Message = "File updated successfully";
                string sd = file.FileName.Substring(file.FileName.Length - 3);
                string p = string.Empty;
                p = Server.MapPath("~/Content/Upload");
                file.SaveAs(p + file.FileName);

                using (db)
                {
                    t.file = file.FileName;
                    db.Entry(t).State = EntityState.Modified;
                    db.SaveChanges();
                }

            }
            return RedirectToAction("List");
        }
        public ActionResult Delete(int id)
        {
            return View(db.Tables.Find(id));

        }
        [HttpPost, ActionName("Delete")]
        public ActionResult delete_conf(int id)
        {
            Table t = db.Tables.Find(id);
            db.Tables.Remove(t);
            db.SaveChanges();
            return RedirectToAction("List");
        }

    }
}

MvcApplication13/Views/FileUpload/Delete.cshtml
@model MvcApplication13.Table

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Table</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.file)
    </div>
    <div class="display-field">
        @*@Html.DisplayFor(model => model.file)*@
        <img src="~/Content/Upload/@Model.file" alt="image" width="100" />
    </div>
</fieldset>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcApplication13/Views/FileUpload/Details.cshtml
@model MvcApplication13.Table

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>Table</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.file)
    </div>
    <div class="display-field">
        @*@Html.DisplayFor(model => model.file)*@
        <img src="~/Content/Upload/@Model.file" alt="image" width="100" />
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "List")
</p>

MvcApplication13/Views/FileUpload/Edit.cshtml
@model MvcApplication13.Table

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Table</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.file)
        </div>
        <div class="editor-field">
            @*@Html.EditorFor(model => model.file)*@
            <input type="file" name="file" />
            <img src="~/Content/Upload/@Model.file" alt="image" width="100" />
            @Html.ValidationMessageFor(model => model.file)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication13/Views/FileUpload/List.cshtml
@model IEnumerable<MvcApplication13.Table>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "submit")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.file)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.file)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

MvcApplication13/Views/FileUpload/submit.cshtml
@model MvcApplication13.Table

@{
    ViewBag.Title = "submit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("submit", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Table</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.file)
        </div>
        <div class="editor-field">
            @*@Html.EditorFor(model => model.file)*@
            <input type="file" name="file" />
            @Html.ValidationMessageFor(model => model.file)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}