MvcApplication13/Controllers/EmployeeController.cs
using MvcApplication13.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Text.RegularExpressions;
using WebMatrix.WebData;

namespace MvcApplication13.Controllers
{
    public class EmployeeController : Controller
    {
        private EmployeeDBEntities _entities = new EmployeeDBEntities();

        // GET: /Employee/

        public ActionResult Index()
        {
            return View(_entities.EmployeeProfiles.ToList());
        }


        [HttpGet]
        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]

        public ActionResult LogIn(Models.EmployeeProfile userr)
        {
            //if (ModelState.IsValid)
            //{
            EmployeeDBEntities employeeDBEntities = new EmployeeDBEntities();
            List<EmployeeProfile> lstEmp = employeeDBEntities.EmployeeProfiles.Where(emp => emp.EMailId == userr.EMailId && emp.Password == userr.Password).ToList();
            if (lstEmp.Count > 0)
            {
                FormsAuthentication.SetAuthCookie(userr.EMailId, false);
                return RedirectToAction("Index", "Hirek");
            }
            else
            {
                ModelState.AddModelError("", "Login details are wrong.");
            }
            return View(userr);
        }


        // GET: /Home/Create 
        [HttpGet]
        public ActionResult Create()
        {

            return View();

        }

        // POST: /Home/Create 
        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]

        public ActionResult Create([Bind(Exclude = "EmpId")] MvcApplication13.Models.EmployeeProfile EmployeeToCreate)
        {

            try
            {

                // TODO: Add insert logic here 
                MvcApplication13.Models.EmployeeDBEntities employeeContext = new Models.EmployeeDBEntities();
                _entities.EmployeeProfiles.Add(EmployeeToCreate);
                _entities.SaveChanges();
                return RedirectToAction("Index");

            }

            catch
            {

                return View();

            }

        }

        // GET: /Home/Edit
        [HttpGet]
        public ActionResult Edit(int id)
        {
            EmployeeProfile employee = new EmployeeDBEntities().EmployeeProfiles.Single(emp => emp.EmpId == id);
            return View(employee);

        }

        //

        // POST: /Home/Edit/5 
        [HttpPost]
        [ActionName("Edit")]
        public ActionResult Edit_Post(EmployeeProfile emp, int id)
        {
            EmployeeDBEntities employeeContext = new EmployeeDBEntities();
            EmployeeProfile employee = employeeContext.EmployeeProfiles.Find(id);
            employee.FirstName = emp.FirstName;
            employee.LastName = emp.LastName;
            employee.EMailId = emp.EMailId;
            employee.Password = emp.Password;
            employee.Gender = emp.Gender;
            employee.PhoneNumber = emp.PhoneNumber;
            employeeContext.Entry(employee).State = EntityState.Modified;

            employeeContext.SaveChanges();

            return RedirectToAction("Index");

            //return View();            
        }
        // GET: /Student/Delete   
        public ActionResult Delete(int id)
        {
            EmployeeProfile employee = _entities.EmployeeProfiles.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }
        // POST: /Student/Delete 
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            EmployeeProfile employee = _entities.EmployeeProfiles.Find(id);
            _entities.EmployeeProfiles.Remove(employee);
            _entities.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            _entities.Dispose();
            base.Dispose(disposing);
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmployeeProfile employee = _entities.EmployeeProfiles.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Hirek");
        }
    }
}

MvcApplication13/Views/Employee/Create.cshtml
@model MvcApplication13.Models.EmployeeProfile

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>EmployeeProfile</legend>

        @*<div class="editor-label">
            @Html.LabelFor(model => model.EmpId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EmpId)
            @Html.ValidationMessageFor(model => model.EmpId)
        </div>*@

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)<br />
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)<br />
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EMailId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EMailId)<br />
            @Html.ValidationMessageFor(model => model.EMailId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Password)<br />
            @Html.ValidationMessageFor(model => model.Password)
        </div>
        

        <div class="editor-label">
            @Html.LabelFor(model => model.PhoneNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PhoneNumber)<br />
            @Html.ValidationMessageFor(model => model.PhoneNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Gender)
        </div>
        @*<div class="editor-field">
            @Html.EditorFor(model => model.Gender)
            @Html.ValidationMessageFor(model => model.Gender)
        </div>*@
        <div class="editor-field">

            @Html.DropDownList("Gender", new List<SelectListItem>
       {
           new SelectListItem{ Text="Male", Value="Male"},
           new SelectListItem{ Text="Female", Value="Female"}
       }, "--- Select ---", new { @class = "form-control" })
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication13/Views/Employee/Delete.cshtml
@model MvcApplication13.Models.EmployeeProfile

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>EmployeeProfile</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EmpId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EmpId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FirstName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FirstName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EMailId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EMailId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Password)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Password)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PhoneNumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PhoneNumber)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Gender)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Gender)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcApplication13/Views/Employee/Details.cshtml
@model MvcApplication13.Models.EmployeeProfile

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>EmployeeProfile</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EmpId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EmpId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FirstName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FirstName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EMailId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EMailId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Password)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Password)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PhoneNumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PhoneNumber)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Gender)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Gender)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcApplication13/Views/Employee/Edit.cshtml
@model MvcApplication13.Models.EmployeeProfile

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>EmployeeProfile</legend>

        @*<div class="editor-label">
            @Html.LabelFor(model => model.EmpId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EmpId)
            @Html.ValidationMessageFor(model => model.EmpId)
        </div>*@

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EMailId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EMailId)
            @Html.ValidationMessageFor(model => model.EMailId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PhoneNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PhoneNumber)
            @Html.ValidationMessageFor(model => model.PhoneNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Gender)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Gender)
            @Html.ValidationMessageFor(model => model.Gender)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication13/Views/Employee/Index.cshtml
@model IEnumerable<MvcApplication13.Models.EmployeeProfile>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@*<table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EmpId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EmpId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }

    </table>*@

MvcApplication13/Views/Employee/LogIn.cshtml
@model MvcApplication13.Models.EmployeeProfile

@{
    ViewBag.Title = "Log in";
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
</hgroup>

@*<section id="loginForm">*@
<p><strong>Use a registered account to log in.</strong></p>
@using (Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Log in Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.EMailId)
                @Html.TextBoxFor(m => m.EMailId)<br />
                @Html.ValidationMessageFor(m => m.EMailId)
            </li>
            <li>
                @Html.LabelFor(m => m.Password)
                @Html.PasswordFor(m => m.Password)<br />
                @Html.ValidationMessageFor(m => m.Password)
            </li>
            
        </ol>

        <input type="submit" value="Log in" />
    </fieldset>
    <p>
        @Html.ActionLink("Create", "Employee") if you don't have an account.
    </p>
    <p>
        @Html.ActionLink("Reset", "ResetPass1") if you forgot password.
    </p>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}